# This workflow will do a clean install, start the selenium server, and run
# all of our tests.

name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
            python-version: '3.x'
            architecture: 'x64'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '16'
      
      - name: Install Dependencies
        run: npm ci
        shell: bash
        
      - name: Build
        run: npm run build
        shell: bash
        
      - name: generate branch name
        run: echo BRANCH=build--$(date +%s) >> $GITHUB_ENV
        
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub CI
          author_email: contact@kaaninan.net
          message: 'CI build'
          new_branch: ${{ env.BRANCH }}
